language: C++
sudo: required

before_install:
  - if cd dealii-installed; then echo Dealii_installation_cached!; else ./install-dealii.sh; fi
  
cache:
  directories:
    - dealii-installed
  
script:
  - export DEAL_II_DIR=$PWD/dealii-installed
  - cmake $PWD/toysolver
  - make
  
