language: C++
sudo: required
  
cache: ccache

script:
  - cd $HOME
  - wget -nc https://github.com/dealii/dealii/releases/download/v8.3.0/dealii-8.3.0.tar.gz
  - tar -xf dealii-8.3.0.tar.gz
  - cd dealii-8.3.0
  - mkdir -p build
  - cd build
  - cmake --DCMAKE_INSTALL_PREFIX=$HOME/dealii-installed ..
  - make compat_files
  - make library
  - make mesh_converter
  - make package
  - make test
  - export DEAL_II_DIR=$HOME/dealii-installed
  - cd $HOME
  - mkdir -p toysolver-build
  - cd toysolver-build
  - cmake $HOME/toysolver
  - make
  
