language: C++
sudo: required

before_install:
  - wget http://apt.biicode.com/install.sh
  - chmod +x install.sh 
  - ./install.sh
  - bii setup:cpp
  - wget -nc https://github.com/dealii/dealii/releases/download/v8.3.0/dealii-8.3.0.tar.gz
  - if cd dealii-8.3.0; then echo Target_exists!; else tar -xvf dealii-8.3.0.tar.gz; fi
  - mkdir -p dealii && cd dealii && cmake --build ../dealii-8.3.0
  - export DEAL_II_DIR=`pwd`
  - git clone https://github.com/koecher/candi
  - cd candi && ./candi.sh
  
script:
  - bii init -L
  - bii cpp:build
