language: C++
sudo: required

before_install:
  - chmod +x install-dealii.sh
  - timeout 2500s ./install-dealii.sh
  - timeout 2500s ./install-dealii.sh
  - timeout 2500s ./install-dealii.sh
  
cache: ccache

script:
  - export DEAL_II_DIR=$PWD/dealii-installed
  - cmake $PWD/toysolver
  - make
  
