language: C++
sudo: required

before_install:
  - wget http://apt.biicode.com/install.sh
  - chmod +x install.sh 
  - ./install.sh
  - bii setup:cpp
  - git clone https://github.com/koecher/candi
  - cd candi && ./candi.sh
  
script:
  - bii init -L
  - bii cpp:build
