language: C++
sudo: required
  
cache: ccache

script:
  - chmod +x install-dealii.sh
  - timeout -s 0 2500s ./install-dealii.sh
  - timeout -s 0 2500s ./install-dealii.sh
  - timeout -s 0 2500s ./install-dealii.sh
  
  - export DEAL_II_DIR=$PWD/dealii-installed
  - cmake $PWD/toysolver
  - make
  
